// <auto-generated />
using System;
using MentalHealthBar.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MentalHealthBar.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251013002037_InitialNodaTime")]
    partial class InitialNodaTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentalHealthBar.Api.Domain.Assessments.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Responses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_assessments_completed");

                    b.HasIndex("Type", "CompletedAt")
                        .HasDatabaseName("idx_assessments_type_completed");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("MentalHealthBar.Api.Domain.Assessments.AssessmentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ScoringRules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("uq_assessment_templates_type");

                    b.ToTable("assessment_templates", (string)null);
                });

            modelBuilder.Entity("MentalHealthBar.Api.Domain.EventLabels.EventLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_event_labels_name")
                        .HasFilter("\"IsDeleted\" = false");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "btree");

                    b.ToTable("event_labels", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventLabel_Name_Length", "LENGTH(\"Name\") > 0 AND LENGTH(\"Name\") <= 50");
                        });
                });

            modelBuilder.Entity("MentalHealthBar.Api.Domain.HealthMetrics.HealthMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedDate")
                        .IsDescending()
                        .HasDatabaseName("idx_health_metrics_date")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Type", "RecordedDate")
                        .IsUnique()
                        .IsDescending()
                        .HasDatabaseName("idx_health_metrics_type_date")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("health_metrics", null, t =>
                        {
                            t.HasCheckConstraint("CK_HealthMetric_Value_Positive", "\"Value\" >= 0");
                        });
                });

            modelBuilder.Entity("MentalHealthBar.Api.Domain.MoodEntries.MoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MoodScore")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Instant>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_mood_entries_recorded")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("mood_entries", (string)null);
                });

            modelBuilder.Entity("MentalHealthBar.Api.Domain.MoodEntries.MoodEntryEventLabel", b =>
                {
                    b.Property<Guid>("MoodEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventLabelId")
                        .HasColumnType("uuid");

                    b.HasKey("MoodEntryId", "EventLabelId");

                    b.HasIndex("EventLabelId");

                    b.HasIndex("MoodEntryId");

                    b.ToTable("mood_entry_event_labels", (string)null);
                });

            modelBuilder.Entity("MentalHealthBar.Api.Domain.MoodEntries.MoodEntryEventLabel", b =>
                {
                    b.HasOne("MentalHealthBar.Api.Domain.EventLabels.EventLabel", "EventLabel")
                        .WithMany("MoodEntryEventLabels")
                        .HasForeignKey("EventLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthBar.Api.Domain.MoodEntries.MoodEntry", "MoodEntry")
                        .WithMany("MoodEntryEventLabels")
                        .HasForeignKey("MoodEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventLabel");

                    b.Navigation("MoodEntry");
                });

            modelBuilder.Entity("MentalHealthBar.Api.Domain.EventLabels.EventLabel", b =>
                {
                    b.Navigation("MoodEntryEventLabels");
                });

            modelBuilder.Entity("MentalHealthBar.Api.Domain.MoodEntries.MoodEntry", b =>
                {
                    b.Navigation("MoodEntryEventLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
